version: "3.7"

services:
  php:
    build:
      args:
        user: ${DOCKER_USER}
        uid: ${DOCKER_UID}
      context: ./
      dockerfile: .docker/php/Dockerfile
    image: csms
    container_name: csms-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - csms
  nginx:
      image: nginx:1.20.2-alpine
      container_name: csms-nginx
      restart: unless-stopped
      ports:
          - ${DOCKER_HTTP_PORT}:80
      volumes:
          - ./:/var/www
          - ./.docker/nginx:/etc/nginx/conf.d
      networks:
          - csms

networks:
  csms:
    driver: bridge
